baseURL = "https://aloralabs.com/"
languageCode = "en-us"
title = "Alora Labs"

enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
inlineImports = true

[build]
writeStats = true

[params]
description = "A Toronto-based product strategy and development agency that lives at the intersection of hardware and digital."
images = ["/apple-touch-icon.png"]

[imaging]
quality = 100

[[menu.main]]
name = "IoT"
url = "/insights/how-to-develop-your-iot-product"
weight = 30

[module]
[[module.mounts]]
source = "node_modules/@openfonts"
target = "static/fonts"
[[module.mounts]]
source = "static"
target = "static"
