[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.111.3"

[context.deploy-preview.environment]
HUGO_VERSION = "0.111.3"

[[redirects]]
from = "https://aloralabs.netlify.com/"
to = "https://aloralabs.com/:splat"
force = true

[[redirects]]
from = "https://aloralab.com/*"
to = "https://aloralabs.com/:splat"
force = true

[[headers]]
for = "*"
[headers.values]
Strict-Transport-Security = "max-age=31536000; preload"
Content-Security-Policy = "object-src 'none'; style-src https: 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Service-Worker-Allowed = "/"
